### ISSUE TITLE
404 on new Location

### ISSUE THREAD

**Issue by pradipta** [cloudyrock/mongock-samples#1]

**Comment by pradipta** [comment]
https://github.com/cloudyrock/mongock-integration-tests/tree/master/mongock-spring-v5/mongock-spring5-springdata3-it

**Comment by dieppa** [comment]
Where did you find that link? It should be :
https://github.com/cloudyrock/mongock-integration-tests/tree/master/mongock-4/mongock-spring-v5/mongock-spring5-springdata3-it

**Comment by pradipta** [comment]
Pull Request: https://github.com/cloudyrock/mongock-samples/pull/2
